export const Images = {
	play: "playCircle",
	heart: "smallHeart",
	share: "share",
	search: "search",
	grid: "grid",
	selectedBookmark: "filledBookmark",
	edit: "edit",
	menu: "bergur",
	home: "home",
	back: "arrowLeft",
	podcast: "headphones",
	twitter: "twitter",
	facebook: "facebook",
	aA: "aA",
	book: "book",
	googlePlus: "googlePlus",
	loginButton: require("./login_button.png"),
	arrowRight: require("./arrowRight.png"),
	subscribeButton: require("./subscribe.png"),
	downloadButton: require("./downloadButton.png"),
	mailBox: require("./mailBox.png"),
	shelf: require("./shelf.png"),
	banner: require("./banner.png"),
	podcastStrip: require("./Rectangle.png"),
	//podcastStrip: require("./podcastBackground.png"),
	//protrait: require("./protrait.png"),
	protrait: require("./defaultImage.jpeg"), 
	square: require("./defaultImage.jpeg"),
	// square: require("./square.png"),
	//landscape: require("./landscape.png"),
	landscape: require("./defaultImage.jpeg"),
	//defaultProfilePic: require("./defaultProilePic.png"),
	defaultProfilePic: require("./noImage.png"),
	closeButton: require("./close.png"),
	ABlogo: require("./AB_White.png"),
	playPodcast: require("./play.png"),
	pause: require("./pause.png"),
	videoBlack: require("./playCircle.png"),
	bookBlack: require("./book.png"),
	podcastBlack: require("./headphones.png"),
	homeBlack: require("./home.png"),
	bergurBlack: require("./bergur.png"),
	videoRed: require("./playCircleGrey.png"),
	bookRed: require("./bookGrey.png"),
	podcastRed: require("./headphonesGrey.png"),
	homeRed: require("./homeGrey.png"),
	bergurRed: require("./bergurGrey.png"),
	loginScreen: require("./ablogo.png"),
	loginScreenNew: require("./newimagebg.png"),
	ABlogoWhite: require("./ArabianBusinessWhite.png"),
	unbookmark: require("./bookmark.png"),
	blackGradient:require("./gradient_black.png"),  
	whiteGradient:require("./gradient_white.png"),
	abLogoBlack:require("./AB_Black.png"),
	menugrey: require("./bergurGrey.png"),
	menuwhite : require("./menu.png"),
	videogrey: require("./video1.png"),
	videowhite : require("./video2.png"),
	homegrey: require("./home1.png"),
	homewhite : require("./home2.png"),
	magzinegrey: require("./magzine1.png"),
	magzinewhite : require("./magzine2.png"), 
	fb_fav:"https://facebook.github.io/react-native/docs/assets/favicon.png",
	subscription_link:"https://www.arabianbusiness.com/subscriptions/index.html",
	contact_us_link:"https://www.arabianbusiness.com/contact-us",
	terms_link : "https://www.itp.com/terms"

};
