export const apis = {
    "check_bookmark": "ws/check-bookmark",
    "article_list":"ws/article-list", 
    "user_preferences":"ws/user-preferences",
    "log_error":"ws/log-error" ,
    "forgot_password":"forgot_password",
    "save_preferences_art_bg":"ws/save-preferences/art-bg",  
    "register":"register",
    "save_preferences_author":"ws/save-preferences/author", 
    "save_preferences_art_font":"ws/save-preferences/art-fontsize",
    "save_bookmark":"ws/save-bookmark", 
    "show_bookmarks":"ws/show-bookmarks/", 
    "brands_listing" :"ws/brands-listing",    
    "save_preferences_brand":"ws/save-preferences/brand",
    "brands_select":"ws/brands_select?_format=json",
    "get_editors_choice":"ws/get-editors-choice",  
    "show_history":"ws/show-history/",
    "save_history":"ws/save-history",  
    "cancel_mag_subscription":"ws/cancel-mag-subscription", 
    "mag_issue_details":"ws/mag-issue-details", 
    "mag_issue_listing" :"ws/mag-issue-listing",
    "save_mag_subscription":"ws/save-mag-subscription",
    "get_mag_subscriptions" :"ws/get-mag-subscriptions",
    "save_preferences_podcast":"ws/save-preferences/podcast",
    "update_user_details":"ws/update-user-details",
    "upload_profile_pic":"ws/upload-profile-pic/",
    "save_notification" :"ws/save-notification",
    "save_preferences_topic" :"ws/save-preferences/topic",  
    "topstories":"ws/topstories", 
    "topics_select":"ws/topics_select?_format=json" 

}